/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as PricingIndexRouteImport } from './routes/pricing/index'
import { Route as HireIndexRouteImport } from './routes/hire/index'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as ChangelogIndexRouteImport } from './routes/changelog/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as UtilsResizableImageIndexRouteImport } from './routes/utils/resizable-image/index'
import { Route as UtilsPixelateImageIndexRouteImport } from './routes/utils/pixelate-image/index'
import { Route as PatternsPaymentFormIndexRouteImport } from './routes/patterns/payment-form/index'
import { Route as PatternsAuthPanelIndexRouteImport } from './routes/patterns/auth-panel/index'
import { Route as LoadersSqueezeIndexRouteImport } from './routes/loaders/squeeze/index'
import { Route as LoadersPreloaderIndexRouteImport } from './routes/loaders/preloader/index'
import { Route as LoadersNeonIndexRouteImport } from './routes/loaders/neon/index'
import { Route as LoadersGusanoIndexRouteImport } from './routes/loaders/gusano/index'
import { Route as LoadersFadeIndexRouteImport } from './routes/loaders/fade/index'
import { Route as DocsQuickStartIndexRouteImport } from './routes/docs/quick-start/index'
import { Route as DocsPhilosophyIndexRouteImport } from './routes/docs/philosophy/index'
import { Route as DocsInstallationIndexRouteImport } from './routes/docs/installation/index'
import { Route as DocsGettingStartedIndexRouteImport } from './routes/docs/getting-started/index'
import { Route as DocsCliIndexRouteImport } from './routes/docs/cli/index'
import { Route as DocsAboutUsIndexRouteImport } from './routes/docs/about-us/index'
import { Route as ComponentsInputsIndexRouteImport } from './routes/components/inputs/index'
import { Route as ComponentsButtonsIndexRouteImport } from './routes/components/buttons/index'
import { Route as ComponentsVideosSimpleVideoComponentIndexRouteImport } from './routes/components/videos/simple-video-component/index'
import { Route as ComponentsInputsInputSelectNumberIndexRouteImport } from './routes/components/inputs/input-select-number/index'
import { Route as ComponentsCardsMagicCardIndexRouteImport } from './routes/components/cards/magic-card/index'
import { Route as ComponentsCardsLetterGlitchCardIndexRouteImport } from './routes/components/cards/letter-glitch-card/index'
import { Route as ComponentsCardsCardHoverIndexRouteImport } from './routes/components/cards/card-hover/index'
import { Route as ComponentsBackgroundsInteractiveParticlesIndexRouteImport } from './routes/components/backgrounds/interactive/particles/index'
import { Route as ComponentsBackgroundsInteractiveParticleFloorIndexRouteImport } from './routes/components/backgrounds/interactive/particle-floor/index'
import { Route as ComponentsBackgroundsInteractiveParallaxStarsIndexRouteImport } from './routes/components/backgrounds/interactive/parallax-stars/index'
import { Route as ComponentsBackgroundsInteractiveIridescenceIndexRouteImport } from './routes/components/backgrounds/interactive/iridescence/index'
import { Route as ComponentsBackgroundsInteractiveHyperspeedIndexRouteImport } from './routes/components/backgrounds/interactive/hyperspeed/index'
import { Route as ComponentsBackgroundsInteractiveDotPatternIndexRouteImport } from './routes/components/backgrounds/interactive/dot-pattern/index'
import { Route as ComponentsBackgroundsInteractiveBallpitIndexRouteImport } from './routes/components/backgrounds/interactive/ballpit/index'
import { Route as ComponentsBackgroundsAnimatedWavyIndexRouteImport } from './routes/components/backgrounds/animated/wavy/index'
import { Route as ComponentsBackgroundsAnimatedSilkIndexRouteImport } from './routes/components/backgrounds/animated/silk/index'
import { Route as ComponentsBackgroundsAnimatedLightningIndexRouteImport } from './routes/components/backgrounds/animated/lightning/index'
import { Route as ComponentsBackgroundsAnimatedGradientIndexRouteImport } from './routes/components/backgrounds/animated/gradient/index'
import { Route as ComponentsBackgroundsAnimatedBubblesIndexRouteImport } from './routes/components/backgrounds/animated/bubbles/index'
import { Route as ComponentsBackgroundsAnimatedAuroraIndexRouteImport } from './routes/components/backgrounds/animated/aurora/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingIndexRoute = PricingIndexRouteImport.update({
  id: '/pricing/',
  path: '/pricing/',
  getParentRoute: () => rootRouteImport,
} as any)
const HireIndexRoute = HireIndexRouteImport.update({
  id: '/hire/',
  path: '/hire/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogIndexRoute = ChangelogIndexRouteImport.update({
  id: '/changelog/',
  path: '/changelog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilsResizableImageIndexRoute =
  UtilsResizableImageIndexRouteImport.update({
    id: '/utils/resizable-image/',
    path: '/utils/resizable-image/',
    getParentRoute: () => rootRouteImport,
  } as any)
const UtilsPixelateImageIndexRoute = UtilsPixelateImageIndexRouteImport.update({
  id: '/utils/pixelate-image/',
  path: '/utils/pixelate-image/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsPaymentFormIndexRoute =
  PatternsPaymentFormIndexRouteImport.update({
    id: '/patterns/payment-form/',
    path: '/patterns/payment-form/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PatternsAuthPanelIndexRoute = PatternsAuthPanelIndexRouteImport.update({
  id: '/patterns/auth-panel/',
  path: '/patterns/auth-panel/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadersSqueezeIndexRoute = LoadersSqueezeIndexRouteImport.update({
  id: '/loaders/squeeze/',
  path: '/loaders/squeeze/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadersPreloaderIndexRoute = LoadersPreloaderIndexRouteImport.update({
  id: '/loaders/preloader/',
  path: '/loaders/preloader/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadersNeonIndexRoute = LoadersNeonIndexRouteImport.update({
  id: '/loaders/neon/',
  path: '/loaders/neon/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadersGusanoIndexRoute = LoadersGusanoIndexRouteImport.update({
  id: '/loaders/gusano/',
  path: '/loaders/gusano/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadersFadeIndexRoute = LoadersFadeIndexRouteImport.update({
  id: '/loaders/fade/',
  path: '/loaders/fade/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsQuickStartIndexRoute = DocsQuickStartIndexRouteImport.update({
  id: '/docs/quick-start/',
  path: '/docs/quick-start/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsPhilosophyIndexRoute = DocsPhilosophyIndexRouteImport.update({
  id: '/docs/philosophy/',
  path: '/docs/philosophy/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsInstallationIndexRoute = DocsInstallationIndexRouteImport.update({
  id: '/docs/installation/',
  path: '/docs/installation/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsGettingStartedIndexRoute = DocsGettingStartedIndexRouteImport.update({
  id: '/docs/getting-started/',
  path: '/docs/getting-started/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCliIndexRoute = DocsCliIndexRouteImport.update({
  id: '/docs/cli/',
  path: '/docs/cli/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsAboutUsIndexRoute = DocsAboutUsIndexRouteImport.update({
  id: '/docs/about-us/',
  path: '/docs/about-us/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsInputsIndexRoute = ComponentsInputsIndexRouteImport.update({
  id: '/components/inputs/',
  path: '/components/inputs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsButtonsIndexRoute = ComponentsButtonsIndexRouteImport.update({
  id: '/components/buttons/',
  path: '/components/buttons/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsVideosSimpleVideoComponentIndexRoute =
  ComponentsVideosSimpleVideoComponentIndexRouteImport.update({
    id: '/components/videos/simple-video-component/',
    path: '/components/videos/simple-video-component/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsInputsInputSelectNumberIndexRoute =
  ComponentsInputsInputSelectNumberIndexRouteImport.update({
    id: '/components/inputs/input-select-number/',
    path: '/components/inputs/input-select-number/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsCardsMagicCardIndexRoute =
  ComponentsCardsMagicCardIndexRouteImport.update({
    id: '/components/cards/magic-card/',
    path: '/components/cards/magic-card/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsCardsLetterGlitchCardIndexRoute =
  ComponentsCardsLetterGlitchCardIndexRouteImport.update({
    id: '/components/cards/letter-glitch-card/',
    path: '/components/cards/letter-glitch-card/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsCardsCardHoverIndexRoute =
  ComponentsCardsCardHoverIndexRouteImport.update({
    id: '/components/cards/card-hover/',
    path: '/components/cards/card-hover/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsBackgroundsInteractiveParticlesIndexRoute =
  ComponentsBackgroundsInteractiveParticlesIndexRouteImport.update({
    id: '/components/backgrounds/interactive/particles/',
    path: '/components/backgrounds/interactive/particles/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsBackgroundsInteractiveParticleFloorIndexRoute =
  ComponentsBackgroundsInteractiveParticleFloorIndexRouteImport.update({
    id: '/components/backgrounds/interactive/particle-floor/',
    path: '/components/backgrounds/interactive/particle-floor/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsBackgroundsInteractiveParallaxStarsIndexRoute =
  ComponentsBackgroundsInteractiveParallaxStarsIndexRouteImport.update({
    id: '/components/backgrounds/interactive/parallax-stars/',
    path: '/components/backgrounds/interactive/parallax-stars/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsBackgroundsInteractiveIridescenceIndexRoute =
  ComponentsBackgroundsInteractiveIridescenceIndexRouteImport.update({
    id: '/components/backgrounds/interactive/iridescence/',
    path: '/components/backgrounds/interactive/iridescence/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsBackgroundsInteractiveHyperspeedIndexRoute =
  ComponentsBackgroundsInteractiveHyperspeedIndexRouteImport.update({
    id: '/components/backgrounds/interactive/hyperspeed/',
    path: '/components/backgrounds/interactive/hyperspeed/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsBackgroundsInteractiveDotPatternIndexRoute =
  ComponentsBackgroundsInteractiveDotPatternIndexRouteImport.update({
    id: '/components/backgrounds/interactive/dot-pattern/',
    path: '/components/backgrounds/interactive/dot-pattern/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsBackgroundsInteractiveBallpitIndexRoute =
  ComponentsBackgroundsInteractiveBallpitIndexRouteImport.update({
    id: '/components/backgrounds/interactive/ballpit/',
    path: '/components/backgrounds/interactive/ballpit/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsBackgroundsAnimatedWavyIndexRoute =
  ComponentsBackgroundsAnimatedWavyIndexRouteImport.update({
    id: '/components/backgrounds/animated/wavy/',
    path: '/components/backgrounds/animated/wavy/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsBackgroundsAnimatedSilkIndexRoute =
  ComponentsBackgroundsAnimatedSilkIndexRouteImport.update({
    id: '/components/backgrounds/animated/silk/',
    path: '/components/backgrounds/animated/silk/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsBackgroundsAnimatedLightningIndexRoute =
  ComponentsBackgroundsAnimatedLightningIndexRouteImport.update({
    id: '/components/backgrounds/animated/lightning/',
    path: '/components/backgrounds/animated/lightning/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsBackgroundsAnimatedGradientIndexRoute =
  ComponentsBackgroundsAnimatedGradientIndexRouteImport.update({
    id: '/components/backgrounds/animated/gradient/',
    path: '/components/backgrounds/animated/gradient/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsBackgroundsAnimatedBubblesIndexRoute =
  ComponentsBackgroundsAnimatedBubblesIndexRouteImport.update({
    id: '/components/backgrounds/animated/bubbles/',
    path: '/components/backgrounds/animated/bubbles/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsBackgroundsAnimatedAuroraIndexRoute =
  ComponentsBackgroundsAnimatedAuroraIndexRouteImport.update({
    id: '/components/backgrounds/animated/aurora/',
    path: '/components/backgrounds/animated/aurora/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthIndexRoute
  '/changelog': typeof ChangelogIndexRoute
  '/components': typeof ComponentsIndexRoute
  '/hire': typeof HireIndexRoute
  '/pricing': typeof PricingIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/components/buttons': typeof ComponentsButtonsIndexRoute
  '/components/inputs': typeof ComponentsInputsIndexRoute
  '/docs/about-us': typeof DocsAboutUsIndexRoute
  '/docs/cli': typeof DocsCliIndexRoute
  '/docs/getting-started': typeof DocsGettingStartedIndexRoute
  '/docs/installation': typeof DocsInstallationIndexRoute
  '/docs/philosophy': typeof DocsPhilosophyIndexRoute
  '/docs/quick-start': typeof DocsQuickStartIndexRoute
  '/loaders/fade': typeof LoadersFadeIndexRoute
  '/loaders/gusano': typeof LoadersGusanoIndexRoute
  '/loaders/neon': typeof LoadersNeonIndexRoute
  '/loaders/preloader': typeof LoadersPreloaderIndexRoute
  '/loaders/squeeze': typeof LoadersSqueezeIndexRoute
  '/patterns/auth-panel': typeof PatternsAuthPanelIndexRoute
  '/patterns/payment-form': typeof PatternsPaymentFormIndexRoute
  '/utils/pixelate-image': typeof UtilsPixelateImageIndexRoute
  '/utils/resizable-image': typeof UtilsResizableImageIndexRoute
  '/components/cards/card-hover': typeof ComponentsCardsCardHoverIndexRoute
  '/components/cards/letter-glitch-card': typeof ComponentsCardsLetterGlitchCardIndexRoute
  '/components/cards/magic-card': typeof ComponentsCardsMagicCardIndexRoute
  '/components/inputs/input-select-number': typeof ComponentsInputsInputSelectNumberIndexRoute
  '/components/videos/simple-video-component': typeof ComponentsVideosSimpleVideoComponentIndexRoute
  '/components/backgrounds/animated/aurora': typeof ComponentsBackgroundsAnimatedAuroraIndexRoute
  '/components/backgrounds/animated/bubbles': typeof ComponentsBackgroundsAnimatedBubblesIndexRoute
  '/components/backgrounds/animated/gradient': typeof ComponentsBackgroundsAnimatedGradientIndexRoute
  '/components/backgrounds/animated/lightning': typeof ComponentsBackgroundsAnimatedLightningIndexRoute
  '/components/backgrounds/animated/silk': typeof ComponentsBackgroundsAnimatedSilkIndexRoute
  '/components/backgrounds/animated/wavy': typeof ComponentsBackgroundsAnimatedWavyIndexRoute
  '/components/backgrounds/interactive/ballpit': typeof ComponentsBackgroundsInteractiveBallpitIndexRoute
  '/components/backgrounds/interactive/dot-pattern': typeof ComponentsBackgroundsInteractiveDotPatternIndexRoute
  '/components/backgrounds/interactive/hyperspeed': typeof ComponentsBackgroundsInteractiveHyperspeedIndexRoute
  '/components/backgrounds/interactive/iridescence': typeof ComponentsBackgroundsInteractiveIridescenceIndexRoute
  '/components/backgrounds/interactive/parallax-stars': typeof ComponentsBackgroundsInteractiveParallaxStarsIndexRoute
  '/components/backgrounds/interactive/particle-floor': typeof ComponentsBackgroundsInteractiveParticleFloorIndexRoute
  '/components/backgrounds/interactive/particles': typeof ComponentsBackgroundsInteractiveParticlesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthIndexRoute
  '/changelog': typeof ChangelogIndexRoute
  '/components': typeof ComponentsIndexRoute
  '/hire': typeof HireIndexRoute
  '/pricing': typeof PricingIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/components/buttons': typeof ComponentsButtonsIndexRoute
  '/components/inputs': typeof ComponentsInputsIndexRoute
  '/docs/about-us': typeof DocsAboutUsIndexRoute
  '/docs/cli': typeof DocsCliIndexRoute
  '/docs/getting-started': typeof DocsGettingStartedIndexRoute
  '/docs/installation': typeof DocsInstallationIndexRoute
  '/docs/philosophy': typeof DocsPhilosophyIndexRoute
  '/docs/quick-start': typeof DocsQuickStartIndexRoute
  '/loaders/fade': typeof LoadersFadeIndexRoute
  '/loaders/gusano': typeof LoadersGusanoIndexRoute
  '/loaders/neon': typeof LoadersNeonIndexRoute
  '/loaders/preloader': typeof LoadersPreloaderIndexRoute
  '/loaders/squeeze': typeof LoadersSqueezeIndexRoute
  '/patterns/auth-panel': typeof PatternsAuthPanelIndexRoute
  '/patterns/payment-form': typeof PatternsPaymentFormIndexRoute
  '/utils/pixelate-image': typeof UtilsPixelateImageIndexRoute
  '/utils/resizable-image': typeof UtilsResizableImageIndexRoute
  '/components/cards/card-hover': typeof ComponentsCardsCardHoverIndexRoute
  '/components/cards/letter-glitch-card': typeof ComponentsCardsLetterGlitchCardIndexRoute
  '/components/cards/magic-card': typeof ComponentsCardsMagicCardIndexRoute
  '/components/inputs/input-select-number': typeof ComponentsInputsInputSelectNumberIndexRoute
  '/components/videos/simple-video-component': typeof ComponentsVideosSimpleVideoComponentIndexRoute
  '/components/backgrounds/animated/aurora': typeof ComponentsBackgroundsAnimatedAuroraIndexRoute
  '/components/backgrounds/animated/bubbles': typeof ComponentsBackgroundsAnimatedBubblesIndexRoute
  '/components/backgrounds/animated/gradient': typeof ComponentsBackgroundsAnimatedGradientIndexRoute
  '/components/backgrounds/animated/lightning': typeof ComponentsBackgroundsAnimatedLightningIndexRoute
  '/components/backgrounds/animated/silk': typeof ComponentsBackgroundsAnimatedSilkIndexRoute
  '/components/backgrounds/animated/wavy': typeof ComponentsBackgroundsAnimatedWavyIndexRoute
  '/components/backgrounds/interactive/ballpit': typeof ComponentsBackgroundsInteractiveBallpitIndexRoute
  '/components/backgrounds/interactive/dot-pattern': typeof ComponentsBackgroundsInteractiveDotPatternIndexRoute
  '/components/backgrounds/interactive/hyperspeed': typeof ComponentsBackgroundsInteractiveHyperspeedIndexRoute
  '/components/backgrounds/interactive/iridescence': typeof ComponentsBackgroundsInteractiveIridescenceIndexRoute
  '/components/backgrounds/interactive/parallax-stars': typeof ComponentsBackgroundsInteractiveParallaxStarsIndexRoute
  '/components/backgrounds/interactive/particle-floor': typeof ComponentsBackgroundsInteractiveParticleFloorIndexRoute
  '/components/backgrounds/interactive/particles': typeof ComponentsBackgroundsInteractiveParticlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/': typeof AuthIndexRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/components/': typeof ComponentsIndexRoute
  '/hire/': typeof HireIndexRoute
  '/pricing/': typeof PricingIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/components/buttons/': typeof ComponentsButtonsIndexRoute
  '/components/inputs/': typeof ComponentsInputsIndexRoute
  '/docs/about-us/': typeof DocsAboutUsIndexRoute
  '/docs/cli/': typeof DocsCliIndexRoute
  '/docs/getting-started/': typeof DocsGettingStartedIndexRoute
  '/docs/installation/': typeof DocsInstallationIndexRoute
  '/docs/philosophy/': typeof DocsPhilosophyIndexRoute
  '/docs/quick-start/': typeof DocsQuickStartIndexRoute
  '/loaders/fade/': typeof LoadersFadeIndexRoute
  '/loaders/gusano/': typeof LoadersGusanoIndexRoute
  '/loaders/neon/': typeof LoadersNeonIndexRoute
  '/loaders/preloader/': typeof LoadersPreloaderIndexRoute
  '/loaders/squeeze/': typeof LoadersSqueezeIndexRoute
  '/patterns/auth-panel/': typeof PatternsAuthPanelIndexRoute
  '/patterns/payment-form/': typeof PatternsPaymentFormIndexRoute
  '/utils/pixelate-image/': typeof UtilsPixelateImageIndexRoute
  '/utils/resizable-image/': typeof UtilsResizableImageIndexRoute
  '/components/cards/card-hover/': typeof ComponentsCardsCardHoverIndexRoute
  '/components/cards/letter-glitch-card/': typeof ComponentsCardsLetterGlitchCardIndexRoute
  '/components/cards/magic-card/': typeof ComponentsCardsMagicCardIndexRoute
  '/components/inputs/input-select-number/': typeof ComponentsInputsInputSelectNumberIndexRoute
  '/components/videos/simple-video-component/': typeof ComponentsVideosSimpleVideoComponentIndexRoute
  '/components/backgrounds/animated/aurora/': typeof ComponentsBackgroundsAnimatedAuroraIndexRoute
  '/components/backgrounds/animated/bubbles/': typeof ComponentsBackgroundsAnimatedBubblesIndexRoute
  '/components/backgrounds/animated/gradient/': typeof ComponentsBackgroundsAnimatedGradientIndexRoute
  '/components/backgrounds/animated/lightning/': typeof ComponentsBackgroundsAnimatedLightningIndexRoute
  '/components/backgrounds/animated/silk/': typeof ComponentsBackgroundsAnimatedSilkIndexRoute
  '/components/backgrounds/animated/wavy/': typeof ComponentsBackgroundsAnimatedWavyIndexRoute
  '/components/backgrounds/interactive/ballpit/': typeof ComponentsBackgroundsInteractiveBallpitIndexRoute
  '/components/backgrounds/interactive/dot-pattern/': typeof ComponentsBackgroundsInteractiveDotPatternIndexRoute
  '/components/backgrounds/interactive/hyperspeed/': typeof ComponentsBackgroundsInteractiveHyperspeedIndexRoute
  '/components/backgrounds/interactive/iridescence/': typeof ComponentsBackgroundsInteractiveIridescenceIndexRoute
  '/components/backgrounds/interactive/parallax-stars/': typeof ComponentsBackgroundsInteractiveParallaxStarsIndexRoute
  '/components/backgrounds/interactive/particle-floor/': typeof ComponentsBackgroundsInteractiveParticleFloorIndexRoute
  '/components/backgrounds/interactive/particles/': typeof ComponentsBackgroundsInteractiveParticlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/changelog'
    | '/components'
    | '/hire'
    | '/pricing'
    | '/templates'
    | '/components/buttons'
    | '/components/inputs'
    | '/docs/about-us'
    | '/docs/cli'
    | '/docs/getting-started'
    | '/docs/installation'
    | '/docs/philosophy'
    | '/docs/quick-start'
    | '/loaders/fade'
    | '/loaders/gusano'
    | '/loaders/neon'
    | '/loaders/preloader'
    | '/loaders/squeeze'
    | '/patterns/auth-panel'
    | '/patterns/payment-form'
    | '/utils/pixelate-image'
    | '/utils/resizable-image'
    | '/components/cards/card-hover'
    | '/components/cards/letter-glitch-card'
    | '/components/cards/magic-card'
    | '/components/inputs/input-select-number'
    | '/components/videos/simple-video-component'
    | '/components/backgrounds/animated/aurora'
    | '/components/backgrounds/animated/bubbles'
    | '/components/backgrounds/animated/gradient'
    | '/components/backgrounds/animated/lightning'
    | '/components/backgrounds/animated/silk'
    | '/components/backgrounds/animated/wavy'
    | '/components/backgrounds/interactive/ballpit'
    | '/components/backgrounds/interactive/dot-pattern'
    | '/components/backgrounds/interactive/hyperspeed'
    | '/components/backgrounds/interactive/iridescence'
    | '/components/backgrounds/interactive/parallax-stars'
    | '/components/backgrounds/interactive/particle-floor'
    | '/components/backgrounds/interactive/particles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/changelog'
    | '/components'
    | '/hire'
    | '/pricing'
    | '/templates'
    | '/components/buttons'
    | '/components/inputs'
    | '/docs/about-us'
    | '/docs/cli'
    | '/docs/getting-started'
    | '/docs/installation'
    | '/docs/philosophy'
    | '/docs/quick-start'
    | '/loaders/fade'
    | '/loaders/gusano'
    | '/loaders/neon'
    | '/loaders/preloader'
    | '/loaders/squeeze'
    | '/patterns/auth-panel'
    | '/patterns/payment-form'
    | '/utils/pixelate-image'
    | '/utils/resizable-image'
    | '/components/cards/card-hover'
    | '/components/cards/letter-glitch-card'
    | '/components/cards/magic-card'
    | '/components/inputs/input-select-number'
    | '/components/videos/simple-video-component'
    | '/components/backgrounds/animated/aurora'
    | '/components/backgrounds/animated/bubbles'
    | '/components/backgrounds/animated/gradient'
    | '/components/backgrounds/animated/lightning'
    | '/components/backgrounds/animated/silk'
    | '/components/backgrounds/animated/wavy'
    | '/components/backgrounds/interactive/ballpit'
    | '/components/backgrounds/interactive/dot-pattern'
    | '/components/backgrounds/interactive/hyperspeed'
    | '/components/backgrounds/interactive/iridescence'
    | '/components/backgrounds/interactive/parallax-stars'
    | '/components/backgrounds/interactive/particle-floor'
    | '/components/backgrounds/interactive/particles'
  id:
    | '__root__'
    | '/'
    | '/auth/'
    | '/changelog/'
    | '/components/'
    | '/hire/'
    | '/pricing/'
    | '/templates/'
    | '/components/buttons/'
    | '/components/inputs/'
    | '/docs/about-us/'
    | '/docs/cli/'
    | '/docs/getting-started/'
    | '/docs/installation/'
    | '/docs/philosophy/'
    | '/docs/quick-start/'
    | '/loaders/fade/'
    | '/loaders/gusano/'
    | '/loaders/neon/'
    | '/loaders/preloader/'
    | '/loaders/squeeze/'
    | '/patterns/auth-panel/'
    | '/patterns/payment-form/'
    | '/utils/pixelate-image/'
    | '/utils/resizable-image/'
    | '/components/cards/card-hover/'
    | '/components/cards/letter-glitch-card/'
    | '/components/cards/magic-card/'
    | '/components/inputs/input-select-number/'
    | '/components/videos/simple-video-component/'
    | '/components/backgrounds/animated/aurora/'
    | '/components/backgrounds/animated/bubbles/'
    | '/components/backgrounds/animated/gradient/'
    | '/components/backgrounds/animated/lightning/'
    | '/components/backgrounds/animated/silk/'
    | '/components/backgrounds/animated/wavy/'
    | '/components/backgrounds/interactive/ballpit/'
    | '/components/backgrounds/interactive/dot-pattern/'
    | '/components/backgrounds/interactive/hyperspeed/'
    | '/components/backgrounds/interactive/iridescence/'
    | '/components/backgrounds/interactive/parallax-stars/'
    | '/components/backgrounds/interactive/particle-floor/'
    | '/components/backgrounds/interactive/particles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthIndexRoute: typeof AuthIndexRoute
  ChangelogIndexRoute: typeof ChangelogIndexRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
  HireIndexRoute: typeof HireIndexRoute
  PricingIndexRoute: typeof PricingIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  ComponentsButtonsIndexRoute: typeof ComponentsButtonsIndexRoute
  ComponentsInputsIndexRoute: typeof ComponentsInputsIndexRoute
  DocsAboutUsIndexRoute: typeof DocsAboutUsIndexRoute
  DocsCliIndexRoute: typeof DocsCliIndexRoute
  DocsGettingStartedIndexRoute: typeof DocsGettingStartedIndexRoute
  DocsInstallationIndexRoute: typeof DocsInstallationIndexRoute
  DocsPhilosophyIndexRoute: typeof DocsPhilosophyIndexRoute
  DocsQuickStartIndexRoute: typeof DocsQuickStartIndexRoute
  LoadersFadeIndexRoute: typeof LoadersFadeIndexRoute
  LoadersGusanoIndexRoute: typeof LoadersGusanoIndexRoute
  LoadersNeonIndexRoute: typeof LoadersNeonIndexRoute
  LoadersPreloaderIndexRoute: typeof LoadersPreloaderIndexRoute
  LoadersSqueezeIndexRoute: typeof LoadersSqueezeIndexRoute
  PatternsAuthPanelIndexRoute: typeof PatternsAuthPanelIndexRoute
  PatternsPaymentFormIndexRoute: typeof PatternsPaymentFormIndexRoute
  UtilsPixelateImageIndexRoute: typeof UtilsPixelateImageIndexRoute
  UtilsResizableImageIndexRoute: typeof UtilsResizableImageIndexRoute
  ComponentsCardsCardHoverIndexRoute: typeof ComponentsCardsCardHoverIndexRoute
  ComponentsCardsLetterGlitchCardIndexRoute: typeof ComponentsCardsLetterGlitchCardIndexRoute
  ComponentsCardsMagicCardIndexRoute: typeof ComponentsCardsMagicCardIndexRoute
  ComponentsInputsInputSelectNumberIndexRoute: typeof ComponentsInputsInputSelectNumberIndexRoute
  ComponentsVideosSimpleVideoComponentIndexRoute: typeof ComponentsVideosSimpleVideoComponentIndexRoute
  ComponentsBackgroundsAnimatedAuroraIndexRoute: typeof ComponentsBackgroundsAnimatedAuroraIndexRoute
  ComponentsBackgroundsAnimatedBubblesIndexRoute: typeof ComponentsBackgroundsAnimatedBubblesIndexRoute
  ComponentsBackgroundsAnimatedGradientIndexRoute: typeof ComponentsBackgroundsAnimatedGradientIndexRoute
  ComponentsBackgroundsAnimatedLightningIndexRoute: typeof ComponentsBackgroundsAnimatedLightningIndexRoute
  ComponentsBackgroundsAnimatedSilkIndexRoute: typeof ComponentsBackgroundsAnimatedSilkIndexRoute
  ComponentsBackgroundsAnimatedWavyIndexRoute: typeof ComponentsBackgroundsAnimatedWavyIndexRoute
  ComponentsBackgroundsInteractiveBallpitIndexRoute: typeof ComponentsBackgroundsInteractiveBallpitIndexRoute
  ComponentsBackgroundsInteractiveDotPatternIndexRoute: typeof ComponentsBackgroundsInteractiveDotPatternIndexRoute
  ComponentsBackgroundsInteractiveHyperspeedIndexRoute: typeof ComponentsBackgroundsInteractiveHyperspeedIndexRoute
  ComponentsBackgroundsInteractiveIridescenceIndexRoute: typeof ComponentsBackgroundsInteractiveIridescenceIndexRoute
  ComponentsBackgroundsInteractiveParallaxStarsIndexRoute: typeof ComponentsBackgroundsInteractiveParallaxStarsIndexRoute
  ComponentsBackgroundsInteractiveParticleFloorIndexRoute: typeof ComponentsBackgroundsInteractiveParticleFloorIndexRoute
  ComponentsBackgroundsInteractiveParticlesIndexRoute: typeof ComponentsBackgroundsInteractiveParticlesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing/': {
      id: '/pricing/'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire/': {
      id: '/hire/'
      path: '/hire'
      fullPath: '/hire'
      preLoaderRoute: typeof HireIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog/': {
      id: '/changelog/'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utils/resizable-image/': {
      id: '/utils/resizable-image/'
      path: '/utils/resizable-image'
      fullPath: '/utils/resizable-image'
      preLoaderRoute: typeof UtilsResizableImageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utils/pixelate-image/': {
      id: '/utils/pixelate-image/'
      path: '/utils/pixelate-image'
      fullPath: '/utils/pixelate-image'
      preLoaderRoute: typeof UtilsPixelateImageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns/payment-form/': {
      id: '/patterns/payment-form/'
      path: '/patterns/payment-form'
      fullPath: '/patterns/payment-form'
      preLoaderRoute: typeof PatternsPaymentFormIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns/auth-panel/': {
      id: '/patterns/auth-panel/'
      path: '/patterns/auth-panel'
      fullPath: '/patterns/auth-panel'
      preLoaderRoute: typeof PatternsAuthPanelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loaders/squeeze/': {
      id: '/loaders/squeeze/'
      path: '/loaders/squeeze'
      fullPath: '/loaders/squeeze'
      preLoaderRoute: typeof LoadersSqueezeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loaders/preloader/': {
      id: '/loaders/preloader/'
      path: '/loaders/preloader'
      fullPath: '/loaders/preloader'
      preLoaderRoute: typeof LoadersPreloaderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loaders/neon/': {
      id: '/loaders/neon/'
      path: '/loaders/neon'
      fullPath: '/loaders/neon'
      preLoaderRoute: typeof LoadersNeonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loaders/gusano/': {
      id: '/loaders/gusano/'
      path: '/loaders/gusano'
      fullPath: '/loaders/gusano'
      preLoaderRoute: typeof LoadersGusanoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loaders/fade/': {
      id: '/loaders/fade/'
      path: '/loaders/fade'
      fullPath: '/loaders/fade'
      preLoaderRoute: typeof LoadersFadeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/quick-start/': {
      id: '/docs/quick-start/'
      path: '/docs/quick-start'
      fullPath: '/docs/quick-start'
      preLoaderRoute: typeof DocsQuickStartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/philosophy/': {
      id: '/docs/philosophy/'
      path: '/docs/philosophy'
      fullPath: '/docs/philosophy'
      preLoaderRoute: typeof DocsPhilosophyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/installation/': {
      id: '/docs/installation/'
      path: '/docs/installation'
      fullPath: '/docs/installation'
      preLoaderRoute: typeof DocsInstallationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/getting-started/': {
      id: '/docs/getting-started/'
      path: '/docs/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsGettingStartedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/cli/': {
      id: '/docs/cli/'
      path: '/docs/cli'
      fullPath: '/docs/cli'
      preLoaderRoute: typeof DocsCliIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/about-us/': {
      id: '/docs/about-us/'
      path: '/docs/about-us'
      fullPath: '/docs/about-us'
      preLoaderRoute: typeof DocsAboutUsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/inputs/': {
      id: '/components/inputs/'
      path: '/components/inputs'
      fullPath: '/components/inputs'
      preLoaderRoute: typeof ComponentsInputsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/buttons/': {
      id: '/components/buttons/'
      path: '/components/buttons'
      fullPath: '/components/buttons'
      preLoaderRoute: typeof ComponentsButtonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/videos/simple-video-component/': {
      id: '/components/videos/simple-video-component/'
      path: '/components/videos/simple-video-component'
      fullPath: '/components/videos/simple-video-component'
      preLoaderRoute: typeof ComponentsVideosSimpleVideoComponentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/inputs/input-select-number/': {
      id: '/components/inputs/input-select-number/'
      path: '/components/inputs/input-select-number'
      fullPath: '/components/inputs/input-select-number'
      preLoaderRoute: typeof ComponentsInputsInputSelectNumberIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/cards/magic-card/': {
      id: '/components/cards/magic-card/'
      path: '/components/cards/magic-card'
      fullPath: '/components/cards/magic-card'
      preLoaderRoute: typeof ComponentsCardsMagicCardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/cards/letter-glitch-card/': {
      id: '/components/cards/letter-glitch-card/'
      path: '/components/cards/letter-glitch-card'
      fullPath: '/components/cards/letter-glitch-card'
      preLoaderRoute: typeof ComponentsCardsLetterGlitchCardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/cards/card-hover/': {
      id: '/components/cards/card-hover/'
      path: '/components/cards/card-hover'
      fullPath: '/components/cards/card-hover'
      preLoaderRoute: typeof ComponentsCardsCardHoverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/backgrounds/interactive/particles/': {
      id: '/components/backgrounds/interactive/particles/'
      path: '/components/backgrounds/interactive/particles'
      fullPath: '/components/backgrounds/interactive/particles'
      preLoaderRoute: typeof ComponentsBackgroundsInteractiveParticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/backgrounds/interactive/particle-floor/': {
      id: '/components/backgrounds/interactive/particle-floor/'
      path: '/components/backgrounds/interactive/particle-floor'
      fullPath: '/components/backgrounds/interactive/particle-floor'
      preLoaderRoute: typeof ComponentsBackgroundsInteractiveParticleFloorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/backgrounds/interactive/parallax-stars/': {
      id: '/components/backgrounds/interactive/parallax-stars/'
      path: '/components/backgrounds/interactive/parallax-stars'
      fullPath: '/components/backgrounds/interactive/parallax-stars'
      preLoaderRoute: typeof ComponentsBackgroundsInteractiveParallaxStarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/backgrounds/interactive/iridescence/': {
      id: '/components/backgrounds/interactive/iridescence/'
      path: '/components/backgrounds/interactive/iridescence'
      fullPath: '/components/backgrounds/interactive/iridescence'
      preLoaderRoute: typeof ComponentsBackgroundsInteractiveIridescenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/backgrounds/interactive/hyperspeed/': {
      id: '/components/backgrounds/interactive/hyperspeed/'
      path: '/components/backgrounds/interactive/hyperspeed'
      fullPath: '/components/backgrounds/interactive/hyperspeed'
      preLoaderRoute: typeof ComponentsBackgroundsInteractiveHyperspeedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/backgrounds/interactive/dot-pattern/': {
      id: '/components/backgrounds/interactive/dot-pattern/'
      path: '/components/backgrounds/interactive/dot-pattern'
      fullPath: '/components/backgrounds/interactive/dot-pattern'
      preLoaderRoute: typeof ComponentsBackgroundsInteractiveDotPatternIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/backgrounds/interactive/ballpit/': {
      id: '/components/backgrounds/interactive/ballpit/'
      path: '/components/backgrounds/interactive/ballpit'
      fullPath: '/components/backgrounds/interactive/ballpit'
      preLoaderRoute: typeof ComponentsBackgroundsInteractiveBallpitIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/backgrounds/animated/wavy/': {
      id: '/components/backgrounds/animated/wavy/'
      path: '/components/backgrounds/animated/wavy'
      fullPath: '/components/backgrounds/animated/wavy'
      preLoaderRoute: typeof ComponentsBackgroundsAnimatedWavyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/backgrounds/animated/silk/': {
      id: '/components/backgrounds/animated/silk/'
      path: '/components/backgrounds/animated/silk'
      fullPath: '/components/backgrounds/animated/silk'
      preLoaderRoute: typeof ComponentsBackgroundsAnimatedSilkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/backgrounds/animated/lightning/': {
      id: '/components/backgrounds/animated/lightning/'
      path: '/components/backgrounds/animated/lightning'
      fullPath: '/components/backgrounds/animated/lightning'
      preLoaderRoute: typeof ComponentsBackgroundsAnimatedLightningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/backgrounds/animated/gradient/': {
      id: '/components/backgrounds/animated/gradient/'
      path: '/components/backgrounds/animated/gradient'
      fullPath: '/components/backgrounds/animated/gradient'
      preLoaderRoute: typeof ComponentsBackgroundsAnimatedGradientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/backgrounds/animated/bubbles/': {
      id: '/components/backgrounds/animated/bubbles/'
      path: '/components/backgrounds/animated/bubbles'
      fullPath: '/components/backgrounds/animated/bubbles'
      preLoaderRoute: typeof ComponentsBackgroundsAnimatedBubblesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/backgrounds/animated/aurora/': {
      id: '/components/backgrounds/animated/aurora/'
      path: '/components/backgrounds/animated/aurora'
      fullPath: '/components/backgrounds/animated/aurora'
      preLoaderRoute: typeof ComponentsBackgroundsAnimatedAuroraIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthIndexRoute: AuthIndexRoute,
  ChangelogIndexRoute: ChangelogIndexRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
  HireIndexRoute: HireIndexRoute,
  PricingIndexRoute: PricingIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  ComponentsButtonsIndexRoute: ComponentsButtonsIndexRoute,
  ComponentsInputsIndexRoute: ComponentsInputsIndexRoute,
  DocsAboutUsIndexRoute: DocsAboutUsIndexRoute,
  DocsCliIndexRoute: DocsCliIndexRoute,
  DocsGettingStartedIndexRoute: DocsGettingStartedIndexRoute,
  DocsInstallationIndexRoute: DocsInstallationIndexRoute,
  DocsPhilosophyIndexRoute: DocsPhilosophyIndexRoute,
  DocsQuickStartIndexRoute: DocsQuickStartIndexRoute,
  LoadersFadeIndexRoute: LoadersFadeIndexRoute,
  LoadersGusanoIndexRoute: LoadersGusanoIndexRoute,
  LoadersNeonIndexRoute: LoadersNeonIndexRoute,
  LoadersPreloaderIndexRoute: LoadersPreloaderIndexRoute,
  LoadersSqueezeIndexRoute: LoadersSqueezeIndexRoute,
  PatternsAuthPanelIndexRoute: PatternsAuthPanelIndexRoute,
  PatternsPaymentFormIndexRoute: PatternsPaymentFormIndexRoute,
  UtilsPixelateImageIndexRoute: UtilsPixelateImageIndexRoute,
  UtilsResizableImageIndexRoute: UtilsResizableImageIndexRoute,
  ComponentsCardsCardHoverIndexRoute: ComponentsCardsCardHoverIndexRoute,
  ComponentsCardsLetterGlitchCardIndexRoute:
    ComponentsCardsLetterGlitchCardIndexRoute,
  ComponentsCardsMagicCardIndexRoute: ComponentsCardsMagicCardIndexRoute,
  ComponentsInputsInputSelectNumberIndexRoute:
    ComponentsInputsInputSelectNumberIndexRoute,
  ComponentsVideosSimpleVideoComponentIndexRoute:
    ComponentsVideosSimpleVideoComponentIndexRoute,
  ComponentsBackgroundsAnimatedAuroraIndexRoute:
    ComponentsBackgroundsAnimatedAuroraIndexRoute,
  ComponentsBackgroundsAnimatedBubblesIndexRoute:
    ComponentsBackgroundsAnimatedBubblesIndexRoute,
  ComponentsBackgroundsAnimatedGradientIndexRoute:
    ComponentsBackgroundsAnimatedGradientIndexRoute,
  ComponentsBackgroundsAnimatedLightningIndexRoute:
    ComponentsBackgroundsAnimatedLightningIndexRoute,
  ComponentsBackgroundsAnimatedSilkIndexRoute:
    ComponentsBackgroundsAnimatedSilkIndexRoute,
  ComponentsBackgroundsAnimatedWavyIndexRoute:
    ComponentsBackgroundsAnimatedWavyIndexRoute,
  ComponentsBackgroundsInteractiveBallpitIndexRoute:
    ComponentsBackgroundsInteractiveBallpitIndexRoute,
  ComponentsBackgroundsInteractiveDotPatternIndexRoute:
    ComponentsBackgroundsInteractiveDotPatternIndexRoute,
  ComponentsBackgroundsInteractiveHyperspeedIndexRoute:
    ComponentsBackgroundsInteractiveHyperspeedIndexRoute,
  ComponentsBackgroundsInteractiveIridescenceIndexRoute:
    ComponentsBackgroundsInteractiveIridescenceIndexRoute,
  ComponentsBackgroundsInteractiveParallaxStarsIndexRoute:
    ComponentsBackgroundsInteractiveParallaxStarsIndexRoute,
  ComponentsBackgroundsInteractiveParticleFloorIndexRoute:
    ComponentsBackgroundsInteractiveParticleFloorIndexRoute,
  ComponentsBackgroundsInteractiveParticlesIndexRoute:
    ComponentsBackgroundsInteractiveParticlesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
