/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as PricingIndexRouteImport } from './routes/pricing/index'
import { Route as HireIndexRouteImport } from './routes/hire/index'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as ChangelogIndexRouteImport } from './routes/changelog/index'
import { Route as DocsQuickStartIndexRouteImport } from './routes/docs/quick-start/index'
import { Route as DocsPhilosophyIndexRouteImport } from './routes/docs/philosophy/index'
import { Route as DocsInstallationIndexRouteImport } from './routes/docs/installation/index'
import { Route as DocsGettingStartedIndexRouteImport } from './routes/docs/getting-started/index'
import { Route as DocsCliIndexRouteImport } from './routes/docs/cli/index'
import { Route as DocsAboutUsIndexRouteImport } from './routes/docs/about-us/index'
import { Route as ComponentsInputsIndexRouteImport } from './routes/components/inputs/index'
import { Route as ComponentsCardsIndexRouteImport } from './routes/components/cards/index'
import { Route as ComponentsButtonsIndexRouteImport } from './routes/components/buttons/index'
import { Route as ComponentsBackgroundsInteractiveParticlesIndexRouteImport } from './routes/components/backgrounds/interactive/particles/index'
import { Route as ComponentsBackgroundsInteractiveParticleFloorIndexRouteImport } from './routes/components/backgrounds/interactive/particle-floor/index'
import { Route as ComponentsBackgroundsInteractiveParallaxStarsIndexRouteImport } from './routes/components/backgrounds/interactive/parallax-stars/index'
import { Route as ComponentsBackgroundsInteractiveIridescenceIndexRouteImport } from './routes/components/backgrounds/interactive/iridescence/index'
import { Route as ComponentsBackgroundsInteractiveHyperspeedIndexRouteImport } from './routes/components/backgrounds/interactive/hyperspeed/index'
import { Route as ComponentsBackgroundsInteractiveDotPatternIndexRouteImport } from './routes/components/backgrounds/interactive/dot-pattern/index'
import { Route as ComponentsBackgroundsInteractiveBallpitIndexRouteImport } from './routes/components/backgrounds/interactive/ballpit/index'
import { Route as ComponentsBackgroundsAnimatedWavyIndexRouteImport } from './routes/components/backgrounds/animated/wavy/index'
import { Route as ComponentsBackgroundsAnimatedSilkIndexRouteImport } from './routes/components/backgrounds/animated/silk/index'
import { Route as ComponentsBackgroundsAnimatedLightningIndexRouteImport } from './routes/components/backgrounds/animated/lightning/index'
import { Route as ComponentsBackgroundsAnimatedGradientIndexRouteImport } from './routes/components/backgrounds/animated/gradient/index'
import { Route as ComponentsBackgroundsAnimatedBubblesIndexRouteImport } from './routes/components/backgrounds/animated/bubbles/index'
import { Route as ComponentsBackgroundsAnimatedAuroraIndexRouteImport } from './routes/components/backgrounds/animated/aurora/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingIndexRoute = PricingIndexRouteImport.update({
  id: '/pricing/',
  path: '/pricing/',
  getParentRoute: () => rootRouteImport,
} as any)
const HireIndexRoute = HireIndexRouteImport.update({
  id: '/hire/',
  path: '/hire/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogIndexRoute = ChangelogIndexRouteImport.update({
  id: '/changelog/',
  path: '/changelog/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsQuickStartIndexRoute = DocsQuickStartIndexRouteImport.update({
  id: '/docs/quick-start/',
  path: '/docs/quick-start/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsPhilosophyIndexRoute = DocsPhilosophyIndexRouteImport.update({
  id: '/docs/philosophy/',
  path: '/docs/philosophy/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsInstallationIndexRoute = DocsInstallationIndexRouteImport.update({
  id: '/docs/installation/',
  path: '/docs/installation/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsGettingStartedIndexRoute = DocsGettingStartedIndexRouteImport.update({
  id: '/docs/getting-started/',
  path: '/docs/getting-started/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCliIndexRoute = DocsCliIndexRouteImport.update({
  id: '/docs/cli/',
  path: '/docs/cli/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsAboutUsIndexRoute = DocsAboutUsIndexRouteImport.update({
  id: '/docs/about-us/',
  path: '/docs/about-us/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsInputsIndexRoute = ComponentsInputsIndexRouteImport.update({
  id: '/components/inputs/',
  path: '/components/inputs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsCardsIndexRoute = ComponentsCardsIndexRouteImport.update({
  id: '/components/cards/',
  path: '/components/cards/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsButtonsIndexRoute = ComponentsButtonsIndexRouteImport.update({
  id: '/components/buttons/',
  path: '/components/buttons/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsBackgroundsInteractiveParticlesIndexRoute =
  ComponentsBackgroundsInteractiveParticlesIndexRouteImport.update({
    id: '/components/backgrounds/interactive/particles/',
    path: '/components/backgrounds/interactive/particles/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsBackgroundsInteractiveParticleFloorIndexRoute =
  ComponentsBackgroundsInteractiveParticleFloorIndexRouteImport.update({
    id: '/components/backgrounds/interactive/particle-floor/',
    path: '/components/backgrounds/interactive/particle-floor/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsBackgroundsInteractiveParallaxStarsIndexRoute =
  ComponentsBackgroundsInteractiveParallaxStarsIndexRouteImport.update({
    id: '/components/backgrounds/interactive/parallax-stars/',
    path: '/components/backgrounds/interactive/parallax-stars/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsBackgroundsInteractiveIridescenceIndexRoute =
  ComponentsBackgroundsInteractiveIridescenceIndexRouteImport.update({
    id: '/components/backgrounds/interactive/iridescence/',
    path: '/components/backgrounds/interactive/iridescence/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsBackgroundsInteractiveHyperspeedIndexRoute =
  ComponentsBackgroundsInteractiveHyperspeedIndexRouteImport.update({
    id: '/components/backgrounds/interactive/hyperspeed/',
    path: '/components/backgrounds/interactive/hyperspeed/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsBackgroundsInteractiveDotPatternIndexRoute =
  ComponentsBackgroundsInteractiveDotPatternIndexRouteImport.update({
    id: '/components/backgrounds/interactive/dot-pattern/',
    path: '/components/backgrounds/interactive/dot-pattern/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsBackgroundsInteractiveBallpitIndexRoute =
  ComponentsBackgroundsInteractiveBallpitIndexRouteImport.update({
    id: '/components/backgrounds/interactive/ballpit/',
    path: '/components/backgrounds/interactive/ballpit/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsBackgroundsAnimatedWavyIndexRoute =
  ComponentsBackgroundsAnimatedWavyIndexRouteImport.update({
    id: '/components/backgrounds/animated/wavy/',
    path: '/components/backgrounds/animated/wavy/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsBackgroundsAnimatedSilkIndexRoute =
  ComponentsBackgroundsAnimatedSilkIndexRouteImport.update({
    id: '/components/backgrounds/animated/silk/',
    path: '/components/backgrounds/animated/silk/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsBackgroundsAnimatedLightningIndexRoute =
  ComponentsBackgroundsAnimatedLightningIndexRouteImport.update({
    id: '/components/backgrounds/animated/lightning/',
    path: '/components/backgrounds/animated/lightning/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsBackgroundsAnimatedGradientIndexRoute =
  ComponentsBackgroundsAnimatedGradientIndexRouteImport.update({
    id: '/components/backgrounds/animated/gradient/',
    path: '/components/backgrounds/animated/gradient/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsBackgroundsAnimatedBubblesIndexRoute =
  ComponentsBackgroundsAnimatedBubblesIndexRouteImport.update({
    id: '/components/backgrounds/animated/bubbles/',
    path: '/components/backgrounds/animated/bubbles/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsBackgroundsAnimatedAuroraIndexRoute =
  ComponentsBackgroundsAnimatedAuroraIndexRouteImport.update({
    id: '/components/backgrounds/animated/aurora/',
    path: '/components/backgrounds/animated/aurora/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogIndexRoute
  '/components': typeof ComponentsIndexRoute
  '/hire': typeof HireIndexRoute
  '/pricing': typeof PricingIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/components/buttons': typeof ComponentsButtonsIndexRoute
  '/components/cards': typeof ComponentsCardsIndexRoute
  '/components/inputs': typeof ComponentsInputsIndexRoute
  '/docs/about-us': typeof DocsAboutUsIndexRoute
  '/docs/cli': typeof DocsCliIndexRoute
  '/docs/getting-started': typeof DocsGettingStartedIndexRoute
  '/docs/installation': typeof DocsInstallationIndexRoute
  '/docs/philosophy': typeof DocsPhilosophyIndexRoute
  '/docs/quick-start': typeof DocsQuickStartIndexRoute
  '/components/backgrounds/animated/aurora': typeof ComponentsBackgroundsAnimatedAuroraIndexRoute
  '/components/backgrounds/animated/bubbles': typeof ComponentsBackgroundsAnimatedBubblesIndexRoute
  '/components/backgrounds/animated/gradient': typeof ComponentsBackgroundsAnimatedGradientIndexRoute
  '/components/backgrounds/animated/lightning': typeof ComponentsBackgroundsAnimatedLightningIndexRoute
  '/components/backgrounds/animated/silk': typeof ComponentsBackgroundsAnimatedSilkIndexRoute
  '/components/backgrounds/animated/wavy': typeof ComponentsBackgroundsAnimatedWavyIndexRoute
  '/components/backgrounds/interactive/ballpit': typeof ComponentsBackgroundsInteractiveBallpitIndexRoute
  '/components/backgrounds/interactive/dot-pattern': typeof ComponentsBackgroundsInteractiveDotPatternIndexRoute
  '/components/backgrounds/interactive/hyperspeed': typeof ComponentsBackgroundsInteractiveHyperspeedIndexRoute
  '/components/backgrounds/interactive/iridescence': typeof ComponentsBackgroundsInteractiveIridescenceIndexRoute
  '/components/backgrounds/interactive/parallax-stars': typeof ComponentsBackgroundsInteractiveParallaxStarsIndexRoute
  '/components/backgrounds/interactive/particle-floor': typeof ComponentsBackgroundsInteractiveParticleFloorIndexRoute
  '/components/backgrounds/interactive/particles': typeof ComponentsBackgroundsInteractiveParticlesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogIndexRoute
  '/components': typeof ComponentsIndexRoute
  '/hire': typeof HireIndexRoute
  '/pricing': typeof PricingIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/components/buttons': typeof ComponentsButtonsIndexRoute
  '/components/cards': typeof ComponentsCardsIndexRoute
  '/components/inputs': typeof ComponentsInputsIndexRoute
  '/docs/about-us': typeof DocsAboutUsIndexRoute
  '/docs/cli': typeof DocsCliIndexRoute
  '/docs/getting-started': typeof DocsGettingStartedIndexRoute
  '/docs/installation': typeof DocsInstallationIndexRoute
  '/docs/philosophy': typeof DocsPhilosophyIndexRoute
  '/docs/quick-start': typeof DocsQuickStartIndexRoute
  '/components/backgrounds/animated/aurora': typeof ComponentsBackgroundsAnimatedAuroraIndexRoute
  '/components/backgrounds/animated/bubbles': typeof ComponentsBackgroundsAnimatedBubblesIndexRoute
  '/components/backgrounds/animated/gradient': typeof ComponentsBackgroundsAnimatedGradientIndexRoute
  '/components/backgrounds/animated/lightning': typeof ComponentsBackgroundsAnimatedLightningIndexRoute
  '/components/backgrounds/animated/silk': typeof ComponentsBackgroundsAnimatedSilkIndexRoute
  '/components/backgrounds/animated/wavy': typeof ComponentsBackgroundsAnimatedWavyIndexRoute
  '/components/backgrounds/interactive/ballpit': typeof ComponentsBackgroundsInteractiveBallpitIndexRoute
  '/components/backgrounds/interactive/dot-pattern': typeof ComponentsBackgroundsInteractiveDotPatternIndexRoute
  '/components/backgrounds/interactive/hyperspeed': typeof ComponentsBackgroundsInteractiveHyperspeedIndexRoute
  '/components/backgrounds/interactive/iridescence': typeof ComponentsBackgroundsInteractiveIridescenceIndexRoute
  '/components/backgrounds/interactive/parallax-stars': typeof ComponentsBackgroundsInteractiveParallaxStarsIndexRoute
  '/components/backgrounds/interactive/particle-floor': typeof ComponentsBackgroundsInteractiveParticleFloorIndexRoute
  '/components/backgrounds/interactive/particles': typeof ComponentsBackgroundsInteractiveParticlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/components/': typeof ComponentsIndexRoute
  '/hire/': typeof HireIndexRoute
  '/pricing/': typeof PricingIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/components/buttons/': typeof ComponentsButtonsIndexRoute
  '/components/cards/': typeof ComponentsCardsIndexRoute
  '/components/inputs/': typeof ComponentsInputsIndexRoute
  '/docs/about-us/': typeof DocsAboutUsIndexRoute
  '/docs/cli/': typeof DocsCliIndexRoute
  '/docs/getting-started/': typeof DocsGettingStartedIndexRoute
  '/docs/installation/': typeof DocsInstallationIndexRoute
  '/docs/philosophy/': typeof DocsPhilosophyIndexRoute
  '/docs/quick-start/': typeof DocsQuickStartIndexRoute
  '/components/backgrounds/animated/aurora/': typeof ComponentsBackgroundsAnimatedAuroraIndexRoute
  '/components/backgrounds/animated/bubbles/': typeof ComponentsBackgroundsAnimatedBubblesIndexRoute
  '/components/backgrounds/animated/gradient/': typeof ComponentsBackgroundsAnimatedGradientIndexRoute
  '/components/backgrounds/animated/lightning/': typeof ComponentsBackgroundsAnimatedLightningIndexRoute
  '/components/backgrounds/animated/silk/': typeof ComponentsBackgroundsAnimatedSilkIndexRoute
  '/components/backgrounds/animated/wavy/': typeof ComponentsBackgroundsAnimatedWavyIndexRoute
  '/components/backgrounds/interactive/ballpit/': typeof ComponentsBackgroundsInteractiveBallpitIndexRoute
  '/components/backgrounds/interactive/dot-pattern/': typeof ComponentsBackgroundsInteractiveDotPatternIndexRoute
  '/components/backgrounds/interactive/hyperspeed/': typeof ComponentsBackgroundsInteractiveHyperspeedIndexRoute
  '/components/backgrounds/interactive/iridescence/': typeof ComponentsBackgroundsInteractiveIridescenceIndexRoute
  '/components/backgrounds/interactive/parallax-stars/': typeof ComponentsBackgroundsInteractiveParallaxStarsIndexRoute
  '/components/backgrounds/interactive/particle-floor/': typeof ComponentsBackgroundsInteractiveParticleFloorIndexRoute
  '/components/backgrounds/interactive/particles/': typeof ComponentsBackgroundsInteractiveParticlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelog'
    | '/components'
    | '/hire'
    | '/pricing'
    | '/templates'
    | '/components/buttons'
    | '/components/cards'
    | '/components/inputs'
    | '/docs/about-us'
    | '/docs/cli'
    | '/docs/getting-started'
    | '/docs/installation'
    | '/docs/philosophy'
    | '/docs/quick-start'
    | '/components/backgrounds/animated/aurora'
    | '/components/backgrounds/animated/bubbles'
    | '/components/backgrounds/animated/gradient'
    | '/components/backgrounds/animated/lightning'
    | '/components/backgrounds/animated/silk'
    | '/components/backgrounds/animated/wavy'
    | '/components/backgrounds/interactive/ballpit'
    | '/components/backgrounds/interactive/dot-pattern'
    | '/components/backgrounds/interactive/hyperspeed'
    | '/components/backgrounds/interactive/iridescence'
    | '/components/backgrounds/interactive/parallax-stars'
    | '/components/backgrounds/interactive/particle-floor'
    | '/components/backgrounds/interactive/particles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/components'
    | '/hire'
    | '/pricing'
    | '/templates'
    | '/components/buttons'
    | '/components/cards'
    | '/components/inputs'
    | '/docs/about-us'
    | '/docs/cli'
    | '/docs/getting-started'
    | '/docs/installation'
    | '/docs/philosophy'
    | '/docs/quick-start'
    | '/components/backgrounds/animated/aurora'
    | '/components/backgrounds/animated/bubbles'
    | '/components/backgrounds/animated/gradient'
    | '/components/backgrounds/animated/lightning'
    | '/components/backgrounds/animated/silk'
    | '/components/backgrounds/animated/wavy'
    | '/components/backgrounds/interactive/ballpit'
    | '/components/backgrounds/interactive/dot-pattern'
    | '/components/backgrounds/interactive/hyperspeed'
    | '/components/backgrounds/interactive/iridescence'
    | '/components/backgrounds/interactive/parallax-stars'
    | '/components/backgrounds/interactive/particle-floor'
    | '/components/backgrounds/interactive/particles'
  id:
    | '__root__'
    | '/'
    | '/changelog/'
    | '/components/'
    | '/hire/'
    | '/pricing/'
    | '/templates/'
    | '/components/buttons/'
    | '/components/cards/'
    | '/components/inputs/'
    | '/docs/about-us/'
    | '/docs/cli/'
    | '/docs/getting-started/'
    | '/docs/installation/'
    | '/docs/philosophy/'
    | '/docs/quick-start/'
    | '/components/backgrounds/animated/aurora/'
    | '/components/backgrounds/animated/bubbles/'
    | '/components/backgrounds/animated/gradient/'
    | '/components/backgrounds/animated/lightning/'
    | '/components/backgrounds/animated/silk/'
    | '/components/backgrounds/animated/wavy/'
    | '/components/backgrounds/interactive/ballpit/'
    | '/components/backgrounds/interactive/dot-pattern/'
    | '/components/backgrounds/interactive/hyperspeed/'
    | '/components/backgrounds/interactive/iridescence/'
    | '/components/backgrounds/interactive/parallax-stars/'
    | '/components/backgrounds/interactive/particle-floor/'
    | '/components/backgrounds/interactive/particles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangelogIndexRoute: typeof ChangelogIndexRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
  HireIndexRoute: typeof HireIndexRoute
  PricingIndexRoute: typeof PricingIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  ComponentsButtonsIndexRoute: typeof ComponentsButtonsIndexRoute
  ComponentsCardsIndexRoute: typeof ComponentsCardsIndexRoute
  ComponentsInputsIndexRoute: typeof ComponentsInputsIndexRoute
  DocsAboutUsIndexRoute: typeof DocsAboutUsIndexRoute
  DocsCliIndexRoute: typeof DocsCliIndexRoute
  DocsGettingStartedIndexRoute: typeof DocsGettingStartedIndexRoute
  DocsInstallationIndexRoute: typeof DocsInstallationIndexRoute
  DocsPhilosophyIndexRoute: typeof DocsPhilosophyIndexRoute
  DocsQuickStartIndexRoute: typeof DocsQuickStartIndexRoute
  ComponentsBackgroundsAnimatedAuroraIndexRoute: typeof ComponentsBackgroundsAnimatedAuroraIndexRoute
  ComponentsBackgroundsAnimatedBubblesIndexRoute: typeof ComponentsBackgroundsAnimatedBubblesIndexRoute
  ComponentsBackgroundsAnimatedGradientIndexRoute: typeof ComponentsBackgroundsAnimatedGradientIndexRoute
  ComponentsBackgroundsAnimatedLightningIndexRoute: typeof ComponentsBackgroundsAnimatedLightningIndexRoute
  ComponentsBackgroundsAnimatedSilkIndexRoute: typeof ComponentsBackgroundsAnimatedSilkIndexRoute
  ComponentsBackgroundsAnimatedWavyIndexRoute: typeof ComponentsBackgroundsAnimatedWavyIndexRoute
  ComponentsBackgroundsInteractiveBallpitIndexRoute: typeof ComponentsBackgroundsInteractiveBallpitIndexRoute
  ComponentsBackgroundsInteractiveDotPatternIndexRoute: typeof ComponentsBackgroundsInteractiveDotPatternIndexRoute
  ComponentsBackgroundsInteractiveHyperspeedIndexRoute: typeof ComponentsBackgroundsInteractiveHyperspeedIndexRoute
  ComponentsBackgroundsInteractiveIridescenceIndexRoute: typeof ComponentsBackgroundsInteractiveIridescenceIndexRoute
  ComponentsBackgroundsInteractiveParallaxStarsIndexRoute: typeof ComponentsBackgroundsInteractiveParallaxStarsIndexRoute
  ComponentsBackgroundsInteractiveParticleFloorIndexRoute: typeof ComponentsBackgroundsInteractiveParticleFloorIndexRoute
  ComponentsBackgroundsInteractiveParticlesIndexRoute: typeof ComponentsBackgroundsInteractiveParticlesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing/': {
      id: '/pricing/'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire/': {
      id: '/hire/'
      path: '/hire'
      fullPath: '/hire'
      preLoaderRoute: typeof HireIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog/': {
      id: '/changelog/'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/quick-start/': {
      id: '/docs/quick-start/'
      path: '/docs/quick-start'
      fullPath: '/docs/quick-start'
      preLoaderRoute: typeof DocsQuickStartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/philosophy/': {
      id: '/docs/philosophy/'
      path: '/docs/philosophy'
      fullPath: '/docs/philosophy'
      preLoaderRoute: typeof DocsPhilosophyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/installation/': {
      id: '/docs/installation/'
      path: '/docs/installation'
      fullPath: '/docs/installation'
      preLoaderRoute: typeof DocsInstallationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/getting-started/': {
      id: '/docs/getting-started/'
      path: '/docs/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsGettingStartedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/cli/': {
      id: '/docs/cli/'
      path: '/docs/cli'
      fullPath: '/docs/cli'
      preLoaderRoute: typeof DocsCliIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/about-us/': {
      id: '/docs/about-us/'
      path: '/docs/about-us'
      fullPath: '/docs/about-us'
      preLoaderRoute: typeof DocsAboutUsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/inputs/': {
      id: '/components/inputs/'
      path: '/components/inputs'
      fullPath: '/components/inputs'
      preLoaderRoute: typeof ComponentsInputsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/cards/': {
      id: '/components/cards/'
      path: '/components/cards'
      fullPath: '/components/cards'
      preLoaderRoute: typeof ComponentsCardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/buttons/': {
      id: '/components/buttons/'
      path: '/components/buttons'
      fullPath: '/components/buttons'
      preLoaderRoute: typeof ComponentsButtonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/backgrounds/interactive/particles/': {
      id: '/components/backgrounds/interactive/particles/'
      path: '/components/backgrounds/interactive/particles'
      fullPath: '/components/backgrounds/interactive/particles'
      preLoaderRoute: typeof ComponentsBackgroundsInteractiveParticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/backgrounds/interactive/particle-floor/': {
      id: '/components/backgrounds/interactive/particle-floor/'
      path: '/components/backgrounds/interactive/particle-floor'
      fullPath: '/components/backgrounds/interactive/particle-floor'
      preLoaderRoute: typeof ComponentsBackgroundsInteractiveParticleFloorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/backgrounds/interactive/parallax-stars/': {
      id: '/components/backgrounds/interactive/parallax-stars/'
      path: '/components/backgrounds/interactive/parallax-stars'
      fullPath: '/components/backgrounds/interactive/parallax-stars'
      preLoaderRoute: typeof ComponentsBackgroundsInteractiveParallaxStarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/backgrounds/interactive/iridescence/': {
      id: '/components/backgrounds/interactive/iridescence/'
      path: '/components/backgrounds/interactive/iridescence'
      fullPath: '/components/backgrounds/interactive/iridescence'
      preLoaderRoute: typeof ComponentsBackgroundsInteractiveIridescenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/backgrounds/interactive/hyperspeed/': {
      id: '/components/backgrounds/interactive/hyperspeed/'
      path: '/components/backgrounds/interactive/hyperspeed'
      fullPath: '/components/backgrounds/interactive/hyperspeed'
      preLoaderRoute: typeof ComponentsBackgroundsInteractiveHyperspeedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/backgrounds/interactive/dot-pattern/': {
      id: '/components/backgrounds/interactive/dot-pattern/'
      path: '/components/backgrounds/interactive/dot-pattern'
      fullPath: '/components/backgrounds/interactive/dot-pattern'
      preLoaderRoute: typeof ComponentsBackgroundsInteractiveDotPatternIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/backgrounds/interactive/ballpit/': {
      id: '/components/backgrounds/interactive/ballpit/'
      path: '/components/backgrounds/interactive/ballpit'
      fullPath: '/components/backgrounds/interactive/ballpit'
      preLoaderRoute: typeof ComponentsBackgroundsInteractiveBallpitIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/backgrounds/animated/wavy/': {
      id: '/components/backgrounds/animated/wavy/'
      path: '/components/backgrounds/animated/wavy'
      fullPath: '/components/backgrounds/animated/wavy'
      preLoaderRoute: typeof ComponentsBackgroundsAnimatedWavyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/backgrounds/animated/silk/': {
      id: '/components/backgrounds/animated/silk/'
      path: '/components/backgrounds/animated/silk'
      fullPath: '/components/backgrounds/animated/silk'
      preLoaderRoute: typeof ComponentsBackgroundsAnimatedSilkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/backgrounds/animated/lightning/': {
      id: '/components/backgrounds/animated/lightning/'
      path: '/components/backgrounds/animated/lightning'
      fullPath: '/components/backgrounds/animated/lightning'
      preLoaderRoute: typeof ComponentsBackgroundsAnimatedLightningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/backgrounds/animated/gradient/': {
      id: '/components/backgrounds/animated/gradient/'
      path: '/components/backgrounds/animated/gradient'
      fullPath: '/components/backgrounds/animated/gradient'
      preLoaderRoute: typeof ComponentsBackgroundsAnimatedGradientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/backgrounds/animated/bubbles/': {
      id: '/components/backgrounds/animated/bubbles/'
      path: '/components/backgrounds/animated/bubbles'
      fullPath: '/components/backgrounds/animated/bubbles'
      preLoaderRoute: typeof ComponentsBackgroundsAnimatedBubblesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/backgrounds/animated/aurora/': {
      id: '/components/backgrounds/animated/aurora/'
      path: '/components/backgrounds/animated/aurora'
      fullPath: '/components/backgrounds/animated/aurora'
      preLoaderRoute: typeof ComponentsBackgroundsAnimatedAuroraIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangelogIndexRoute: ChangelogIndexRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
  HireIndexRoute: HireIndexRoute,
  PricingIndexRoute: PricingIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  ComponentsButtonsIndexRoute: ComponentsButtonsIndexRoute,
  ComponentsCardsIndexRoute: ComponentsCardsIndexRoute,
  ComponentsInputsIndexRoute: ComponentsInputsIndexRoute,
  DocsAboutUsIndexRoute: DocsAboutUsIndexRoute,
  DocsCliIndexRoute: DocsCliIndexRoute,
  DocsGettingStartedIndexRoute: DocsGettingStartedIndexRoute,
  DocsInstallationIndexRoute: DocsInstallationIndexRoute,
  DocsPhilosophyIndexRoute: DocsPhilosophyIndexRoute,
  DocsQuickStartIndexRoute: DocsQuickStartIndexRoute,
  ComponentsBackgroundsAnimatedAuroraIndexRoute:
    ComponentsBackgroundsAnimatedAuroraIndexRoute,
  ComponentsBackgroundsAnimatedBubblesIndexRoute:
    ComponentsBackgroundsAnimatedBubblesIndexRoute,
  ComponentsBackgroundsAnimatedGradientIndexRoute:
    ComponentsBackgroundsAnimatedGradientIndexRoute,
  ComponentsBackgroundsAnimatedLightningIndexRoute:
    ComponentsBackgroundsAnimatedLightningIndexRoute,
  ComponentsBackgroundsAnimatedSilkIndexRoute:
    ComponentsBackgroundsAnimatedSilkIndexRoute,
  ComponentsBackgroundsAnimatedWavyIndexRoute:
    ComponentsBackgroundsAnimatedWavyIndexRoute,
  ComponentsBackgroundsInteractiveBallpitIndexRoute:
    ComponentsBackgroundsInteractiveBallpitIndexRoute,
  ComponentsBackgroundsInteractiveDotPatternIndexRoute:
    ComponentsBackgroundsInteractiveDotPatternIndexRoute,
  ComponentsBackgroundsInteractiveHyperspeedIndexRoute:
    ComponentsBackgroundsInteractiveHyperspeedIndexRoute,
  ComponentsBackgroundsInteractiveIridescenceIndexRoute:
    ComponentsBackgroundsInteractiveIridescenceIndexRoute,
  ComponentsBackgroundsInteractiveParallaxStarsIndexRoute:
    ComponentsBackgroundsInteractiveParallaxStarsIndexRoute,
  ComponentsBackgroundsInteractiveParticleFloorIndexRoute:
    ComponentsBackgroundsInteractiveParticleFloorIndexRoute,
  ComponentsBackgroundsInteractiveParticlesIndexRoute:
    ComponentsBackgroundsInteractiveParticlesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
