/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as PricingIndexRouteImport } from './routes/pricing/index'
import { Route as HireIndexRouteImport } from './routes/hire/index'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as ChangelogIndexRouteImport } from './routes/changelog/index'
import { Route as DocsQuickStartIndexRouteImport } from './routes/docs/quick-start/index'
import { Route as DocsPhilosophyIndexRouteImport } from './routes/docs/philosophy/index'
import { Route as DocsInstallationIndexRouteImport } from './routes/docs/installation/index'
import { Route as DocsGettingStartedIndexRouteImport } from './routes/docs/getting-started/index'
import { Route as DocsCliIndexRouteImport } from './routes/docs/cli/index'
import { Route as DocsAboutUsIndexRouteImport } from './routes/docs/about-us/index'
import { Route as ComponentsInputsIndexRouteImport } from './routes/components/inputs/index'
import { Route as ComponentsCardsIndexRouteImport } from './routes/components/cards/index'
import { Route as ComponentsButtonsIndexRouteImport } from './routes/components/buttons/index'
import { Route as ComponentsBackgroundsInteractiveParallaxStarsIndexRouteImport } from './routes/components/backgrounds/interactive/parallax-stars/index'
import { Route as ComponentsBackgroundsInteractiveDotPatternIndexRouteImport } from './routes/components/backgrounds/interactive/dot-pattern/index'
import { Route as ComponentsBackgroundsInteractiveAuroraGradientIndexRouteImport } from './routes/components/backgrounds/interactive/aurora-gradient/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingIndexRoute = PricingIndexRouteImport.update({
  id: '/pricing/',
  path: '/pricing/',
  getParentRoute: () => rootRouteImport,
} as any)
const HireIndexRoute = HireIndexRouteImport.update({
  id: '/hire/',
  path: '/hire/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogIndexRoute = ChangelogIndexRouteImport.update({
  id: '/changelog/',
  path: '/changelog/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsQuickStartIndexRoute = DocsQuickStartIndexRouteImport.update({
  id: '/docs/quick-start/',
  path: '/docs/quick-start/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsPhilosophyIndexRoute = DocsPhilosophyIndexRouteImport.update({
  id: '/docs/philosophy/',
  path: '/docs/philosophy/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsInstallationIndexRoute = DocsInstallationIndexRouteImport.update({
  id: '/docs/installation/',
  path: '/docs/installation/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsGettingStartedIndexRoute = DocsGettingStartedIndexRouteImport.update({
  id: '/docs/getting-started/',
  path: '/docs/getting-started/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCliIndexRoute = DocsCliIndexRouteImport.update({
  id: '/docs/cli/',
  path: '/docs/cli/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsAboutUsIndexRoute = DocsAboutUsIndexRouteImport.update({
  id: '/docs/about-us/',
  path: '/docs/about-us/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsInputsIndexRoute = ComponentsInputsIndexRouteImport.update({
  id: '/components/inputs/',
  path: '/components/inputs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsCardsIndexRoute = ComponentsCardsIndexRouteImport.update({
  id: '/components/cards/',
  path: '/components/cards/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsButtonsIndexRoute = ComponentsButtonsIndexRouteImport.update({
  id: '/components/buttons/',
  path: '/components/buttons/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsBackgroundsInteractiveParallaxStarsIndexRoute =
  ComponentsBackgroundsInteractiveParallaxStarsIndexRouteImport.update({
    id: '/components/backgrounds/interactive/parallax-stars/',
    path: '/components/backgrounds/interactive/parallax-stars/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsBackgroundsInteractiveDotPatternIndexRoute =
  ComponentsBackgroundsInteractiveDotPatternIndexRouteImport.update({
    id: '/components/backgrounds/interactive/dot-pattern/',
    path: '/components/backgrounds/interactive/dot-pattern/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsBackgroundsInteractiveAuroraGradientIndexRoute =
  ComponentsBackgroundsInteractiveAuroraGradientIndexRouteImport.update({
    id: '/components/backgrounds/interactive/aurora-gradient/',
    path: '/components/backgrounds/interactive/aurora-gradient/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogIndexRoute
  '/components': typeof ComponentsIndexRoute
  '/hire': typeof HireIndexRoute
  '/pricing': typeof PricingIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/components/buttons': typeof ComponentsButtonsIndexRoute
  '/components/cards': typeof ComponentsCardsIndexRoute
  '/components/inputs': typeof ComponentsInputsIndexRoute
  '/docs/about-us': typeof DocsAboutUsIndexRoute
  '/docs/cli': typeof DocsCliIndexRoute
  '/docs/getting-started': typeof DocsGettingStartedIndexRoute
  '/docs/installation': typeof DocsInstallationIndexRoute
  '/docs/philosophy': typeof DocsPhilosophyIndexRoute
  '/docs/quick-start': typeof DocsQuickStartIndexRoute
  '/components/backgrounds/interactive/aurora-gradient': typeof ComponentsBackgroundsInteractiveAuroraGradientIndexRoute
  '/components/backgrounds/interactive/dot-pattern': typeof ComponentsBackgroundsInteractiveDotPatternIndexRoute
  '/components/backgrounds/interactive/parallax-stars': typeof ComponentsBackgroundsInteractiveParallaxStarsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogIndexRoute
  '/components': typeof ComponentsIndexRoute
  '/hire': typeof HireIndexRoute
  '/pricing': typeof PricingIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/components/buttons': typeof ComponentsButtonsIndexRoute
  '/components/cards': typeof ComponentsCardsIndexRoute
  '/components/inputs': typeof ComponentsInputsIndexRoute
  '/docs/about-us': typeof DocsAboutUsIndexRoute
  '/docs/cli': typeof DocsCliIndexRoute
  '/docs/getting-started': typeof DocsGettingStartedIndexRoute
  '/docs/installation': typeof DocsInstallationIndexRoute
  '/docs/philosophy': typeof DocsPhilosophyIndexRoute
  '/docs/quick-start': typeof DocsQuickStartIndexRoute
  '/components/backgrounds/interactive/aurora-gradient': typeof ComponentsBackgroundsInteractiveAuroraGradientIndexRoute
  '/components/backgrounds/interactive/dot-pattern': typeof ComponentsBackgroundsInteractiveDotPatternIndexRoute
  '/components/backgrounds/interactive/parallax-stars': typeof ComponentsBackgroundsInteractiveParallaxStarsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/components/': typeof ComponentsIndexRoute
  '/hire/': typeof HireIndexRoute
  '/pricing/': typeof PricingIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/components/buttons/': typeof ComponentsButtonsIndexRoute
  '/components/cards/': typeof ComponentsCardsIndexRoute
  '/components/inputs/': typeof ComponentsInputsIndexRoute
  '/docs/about-us/': typeof DocsAboutUsIndexRoute
  '/docs/cli/': typeof DocsCliIndexRoute
  '/docs/getting-started/': typeof DocsGettingStartedIndexRoute
  '/docs/installation/': typeof DocsInstallationIndexRoute
  '/docs/philosophy/': typeof DocsPhilosophyIndexRoute
  '/docs/quick-start/': typeof DocsQuickStartIndexRoute
  '/components/backgrounds/interactive/aurora-gradient/': typeof ComponentsBackgroundsInteractiveAuroraGradientIndexRoute
  '/components/backgrounds/interactive/dot-pattern/': typeof ComponentsBackgroundsInteractiveDotPatternIndexRoute
  '/components/backgrounds/interactive/parallax-stars/': typeof ComponentsBackgroundsInteractiveParallaxStarsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelog'
    | '/components'
    | '/hire'
    | '/pricing'
    | '/templates'
    | '/components/buttons'
    | '/components/cards'
    | '/components/inputs'
    | '/docs/about-us'
    | '/docs/cli'
    | '/docs/getting-started'
    | '/docs/installation'
    | '/docs/philosophy'
    | '/docs/quick-start'
    | '/components/backgrounds/interactive/aurora-gradient'
    | '/components/backgrounds/interactive/dot-pattern'
    | '/components/backgrounds/interactive/parallax-stars'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/components'
    | '/hire'
    | '/pricing'
    | '/templates'
    | '/components/buttons'
    | '/components/cards'
    | '/components/inputs'
    | '/docs/about-us'
    | '/docs/cli'
    | '/docs/getting-started'
    | '/docs/installation'
    | '/docs/philosophy'
    | '/docs/quick-start'
    | '/components/backgrounds/interactive/aurora-gradient'
    | '/components/backgrounds/interactive/dot-pattern'
    | '/components/backgrounds/interactive/parallax-stars'
  id:
    | '__root__'
    | '/'
    | '/changelog/'
    | '/components/'
    | '/hire/'
    | '/pricing/'
    | '/templates/'
    | '/components/buttons/'
    | '/components/cards/'
    | '/components/inputs/'
    | '/docs/about-us/'
    | '/docs/cli/'
    | '/docs/getting-started/'
    | '/docs/installation/'
    | '/docs/philosophy/'
    | '/docs/quick-start/'
    | '/components/backgrounds/interactive/aurora-gradient/'
    | '/components/backgrounds/interactive/dot-pattern/'
    | '/components/backgrounds/interactive/parallax-stars/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangelogIndexRoute: typeof ChangelogIndexRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
  HireIndexRoute: typeof HireIndexRoute
  PricingIndexRoute: typeof PricingIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  ComponentsButtonsIndexRoute: typeof ComponentsButtonsIndexRoute
  ComponentsCardsIndexRoute: typeof ComponentsCardsIndexRoute
  ComponentsInputsIndexRoute: typeof ComponentsInputsIndexRoute
  DocsAboutUsIndexRoute: typeof DocsAboutUsIndexRoute
  DocsCliIndexRoute: typeof DocsCliIndexRoute
  DocsGettingStartedIndexRoute: typeof DocsGettingStartedIndexRoute
  DocsInstallationIndexRoute: typeof DocsInstallationIndexRoute
  DocsPhilosophyIndexRoute: typeof DocsPhilosophyIndexRoute
  DocsQuickStartIndexRoute: typeof DocsQuickStartIndexRoute
  ComponentsBackgroundsInteractiveAuroraGradientIndexRoute: typeof ComponentsBackgroundsInteractiveAuroraGradientIndexRoute
  ComponentsBackgroundsInteractiveDotPatternIndexRoute: typeof ComponentsBackgroundsInteractiveDotPatternIndexRoute
  ComponentsBackgroundsInteractiveParallaxStarsIndexRoute: typeof ComponentsBackgroundsInteractiveParallaxStarsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing/': {
      id: '/pricing/'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire/': {
      id: '/hire/'
      path: '/hire'
      fullPath: '/hire'
      preLoaderRoute: typeof HireIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog/': {
      id: '/changelog/'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/quick-start/': {
      id: '/docs/quick-start/'
      path: '/docs/quick-start'
      fullPath: '/docs/quick-start'
      preLoaderRoute: typeof DocsQuickStartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/philosophy/': {
      id: '/docs/philosophy/'
      path: '/docs/philosophy'
      fullPath: '/docs/philosophy'
      preLoaderRoute: typeof DocsPhilosophyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/installation/': {
      id: '/docs/installation/'
      path: '/docs/installation'
      fullPath: '/docs/installation'
      preLoaderRoute: typeof DocsInstallationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/getting-started/': {
      id: '/docs/getting-started/'
      path: '/docs/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsGettingStartedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/cli/': {
      id: '/docs/cli/'
      path: '/docs/cli'
      fullPath: '/docs/cli'
      preLoaderRoute: typeof DocsCliIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/about-us/': {
      id: '/docs/about-us/'
      path: '/docs/about-us'
      fullPath: '/docs/about-us'
      preLoaderRoute: typeof DocsAboutUsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/inputs/': {
      id: '/components/inputs/'
      path: '/components/inputs'
      fullPath: '/components/inputs'
      preLoaderRoute: typeof ComponentsInputsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/cards/': {
      id: '/components/cards/'
      path: '/components/cards'
      fullPath: '/components/cards'
      preLoaderRoute: typeof ComponentsCardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/buttons/': {
      id: '/components/buttons/'
      path: '/components/buttons'
      fullPath: '/components/buttons'
      preLoaderRoute: typeof ComponentsButtonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/backgrounds/interactive/parallax-stars/': {
      id: '/components/backgrounds/interactive/parallax-stars/'
      path: '/components/backgrounds/interactive/parallax-stars'
      fullPath: '/components/backgrounds/interactive/parallax-stars'
      preLoaderRoute: typeof ComponentsBackgroundsInteractiveParallaxStarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/backgrounds/interactive/dot-pattern/': {
      id: '/components/backgrounds/interactive/dot-pattern/'
      path: '/components/backgrounds/interactive/dot-pattern'
      fullPath: '/components/backgrounds/interactive/dot-pattern'
      preLoaderRoute: typeof ComponentsBackgroundsInteractiveDotPatternIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/backgrounds/interactive/aurora-gradient/': {
      id: '/components/backgrounds/interactive/aurora-gradient/'
      path: '/components/backgrounds/interactive/aurora-gradient'
      fullPath: '/components/backgrounds/interactive/aurora-gradient'
      preLoaderRoute: typeof ComponentsBackgroundsInteractiveAuroraGradientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangelogIndexRoute: ChangelogIndexRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
  HireIndexRoute: HireIndexRoute,
  PricingIndexRoute: PricingIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  ComponentsButtonsIndexRoute: ComponentsButtonsIndexRoute,
  ComponentsCardsIndexRoute: ComponentsCardsIndexRoute,
  ComponentsInputsIndexRoute: ComponentsInputsIndexRoute,
  DocsAboutUsIndexRoute: DocsAboutUsIndexRoute,
  DocsCliIndexRoute: DocsCliIndexRoute,
  DocsGettingStartedIndexRoute: DocsGettingStartedIndexRoute,
  DocsInstallationIndexRoute: DocsInstallationIndexRoute,
  DocsPhilosophyIndexRoute: DocsPhilosophyIndexRoute,
  DocsQuickStartIndexRoute: DocsQuickStartIndexRoute,
  ComponentsBackgroundsInteractiveAuroraGradientIndexRoute:
    ComponentsBackgroundsInteractiveAuroraGradientIndexRoute,
  ComponentsBackgroundsInteractiveDotPatternIndexRoute:
    ComponentsBackgroundsInteractiveDotPatternIndexRoute,
  ComponentsBackgroundsInteractiveParallaxStarsIndexRoute:
    ComponentsBackgroundsInteractiveParallaxStarsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
